var _map_get = Map.prototype.get;
Map.prototype.get = function(key){
    // 判断key对象是否是代理对象, 如果是代理对象. 获取到原始对象
    // js里面不存在这种东西
    let val = _map_get.call(this, key);
    if(val){
        return val;
    }

    let tmp = key;
    // 虚拟的定义某个属性

    while(true){
        let obj = tmp.__tar________get__;
        if (!obj){
            return _map_get.call(this, tmp);
        }
        tmp = obj;
    }

    // let v = _map_get.call(this, key);
    // if(v){
    //     return v;
    // }

    // let obj = key.__tar________get__;
    // if(obj){
    //     return _map_get.call(this, obj);
    // } else {
    //     return _map_get.call(this, key);
    // }
}

globalThis.my_env = {
    // 关于函数处理的插件
    // 关于代理的插件
    // 处理toString
    plugins: {},
    basic_info: {
        pgs: [
            {
                name: "Chrome PDF Viewer",
                description: "Portable Document Format",
                filename: "internal-pdf-viewer",
                length: 2
            },
            {
                name: "Chromium PDF Viewer",
                description: "Portable Document Format",
                filename: "internal-pdf-viewer",
                length: 2
            },
            {
                name: "Microsoft Edge PDF Viewer",
                description: "Portable Document Format",
                filename: "internal-pdf-viewer",
                length: 2
            },
            {
                name: "PDF Viewer",
                description: "Portable Document Format",
                filename: "internal-pdf-viewer",
                length: 2
            },
            {
                name: "WebKit built-in PDF",
                description: "Portable Document Format",
                filename: "internal-pdf-viewer",
                length: 2
            },
        ],
        mms: [
            {
                "type": "application/pdf",
                "suffixes": "pdf",
                "description": "description",
            },
            {
                "type": "text/pdf",
                "suffixes": "pdf",
                "description": "description",
            }
        ],
    },

    // memery负责保存整个浏览器中所有的需要存储在内存中的数据
    memory: {
        location: {}, // location中的内容, 随着页面的变化而变化的. 具体的内容放在start.js中
        navigator: {
            "vendorSub": "",
            "productSub": "20030107",
            "vendor": "Google Inc.",
            "maxTouchPoints": 0,
            "scheduling": {},
            "userActivation": {},
            "doNotTrack": "1",
            "geolocation": {},
            "connection": {},
            "plugins": null,
            "mimeTypes": null,
            "pdfViewerEnabled": true,
            "webkitTemporaryStorage": {},
            "webkitPersistentStorage": {},
            "windowControlsOverlay": {},
            "hardwareConcurrency": 20,
            "cookieEnabled": true,
            "appCodeName": "Mozilla",
            "appName": "Netscape",
            "appVersion": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
            "platform": "Win32",
            "product": "Gecko",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
            "language": "zh-CN",
            "languages": ["zh-CN", "zh", "en"],
            "onLine": true,
            "webdriver": false,
            "deprecatedRunAdAuctionEnforcesKAnonymity": false,
            "protectedAudience": {},
            "bluetooth": {},
            "storageBuckets": {},
            "clipboard": {},
            "credentials": {},
            "keyboard": {},
            "managed": {},
            "mediaDevices": {},
            "storage": {},
            "serviceWorker": {},
            "virtualKeyboard": {},
            "wakeLock": {},
            "deviceMemory": 8,
            "userAgentData": {
                "brands": [{"brand": "Google Chrome", "version": "131"}, {
                    "brand": "Chromium",
                    "version": "131"
                }, {"brand": "Not_A Brand", "version": "24"}], "mobile": false, "platform": "Windows"
            },
            "login": {},
            "ink": {},
            "mediaCapabilities": {},
            "hid": {},
            "locks": {},
            "gpu": {},
            "mediaSession": {},
            "permissions": {},
            "presentation": {},
            "usb": {},
            "xr": {},
            "serial": {}
        },

        // storage的数据已经存储在对象身上了. 这里就不用了.
        // storage: new Map(), // storage的数据已经存储在对象身上了. 这里就不用了.

        pgs: new Map(), // {plugin对象: {基础数据}}
        mms: new Map(), // {mimetype对象: {基础数据}}

        // 事件监听...
        listeners: new Map(),
        // 保存 事件对象: 事件对象的数据
        events: new Map(), // {事件对象: 事件的数据}
        // dom元素...
        nodes: new Map(), // {dom对象:dom节点数据}
        // 存储cookie信息
        cookies: {},
        wins: new Map(),
        xhr: new Map(), // {xhr: 数据}
        dom_cvs: new Map(),// {dom对象: 画图的canvas对象}   77 99
        dom_cvs_ctx: new Map(), //{dom的canvas对象:  浏览器的ctx}
        my_ctx_ctx: new Map(), // {我的ctx对象: 真正画图的ctx}
        // 所有的样式的初始化的时候的状态
        init_style: {
            "accentColor": "",
            "additiveSymbols": "",
            "alignContent": "",
            "alignItems": "",
            "alignSelf": "",
            "alignmentBaseline": "",
            "all": "",
            "animation": "",
            "animationComposition": "",
            "animationDelay": "",
            "animationDirection": "",
            "animationDuration": "",
            "animationFillMode": "",
            "animationIterationCount": "",
            "animationName": "",
            "animationPlayState": "",
            "animationTimingFunction": "",
            "appRegion": "",
            "appearance": "",
            "ascentOverride": "",
            "aspectRatio": "",
            "backdropFilter": "",
            "backfaceVisibility": "",
            "background": "",
            "backgroundAttachment": "",
            "backgroundBlendMode": "",
            "backgroundClip": "",
            "backgroundColor": "",
            "backgroundImage": "",
            "backgroundOrigin": "",
            "backgroundPosition": "",
            "backgroundPositionX": "",
            "backgroundPositionY": "",
            "backgroundRepeat": "",
            "backgroundRepeatX": "",
            "backgroundRepeatY": "",
            "backgroundSize": "",
            "basePalette": "",
            "baselineShift": "",
            "baselineSource": "",
            "blockSize": "",
            "border": "",
            "borderBlock": "",
            "borderBlockColor": "",
            "borderBlockEnd": "",
            "borderBlockEndColor": "",
            "borderBlockEndStyle": "",
            "borderBlockEndWidth": "",
            "borderBlockStart": "",
            "borderBlockStartColor": "",
            "borderBlockStartStyle": "",
            "borderBlockStartWidth": "",
            "borderBlockStyle": "",
            "borderBlockWidth": "",
            "borderBottom": "",
            "borderBottomColor": "",
            "borderBottomLeftRadius": "",
            "borderBottomRightRadius": "",
            "borderBottomStyle": "",
            "borderBottomWidth": "",
            "borderCollapse": "",
            "borderColor": "",
            "borderEndEndRadius": "",
            "borderEndStartRadius": "",
            "borderImage": "",
            "borderImageOutset": "",
            "borderImageRepeat": "",
            "borderImageSlice": "",
            "borderImageSource": "",
            "borderImageWidth": "",
            "borderInline": "",
            "borderInlineColor": "",
            "borderInlineEnd": "",
            "borderInlineEndColor": "",
            "borderInlineEndStyle": "",
            "borderInlineEndWidth": "",
            "borderInlineStart": "",
            "borderInlineStartColor": "",
            "borderInlineStartStyle": "",
            "borderInlineStartWidth": "",
            "borderInlineStyle": "",
            "borderInlineWidth": "",
            "borderLeft": "",
            "borderLeftColor": "",
            "borderLeftStyle": "",
            "borderLeftWidth": "",
            "borderRadius": "",
            "borderRight": "",
            "borderRightColor": "",
            "borderRightStyle": "",
            "borderRightWidth": "",
            "borderSpacing": "",
            "borderStartEndRadius": "",
            "borderStartStartRadius": "",
            "borderStyle": "",
            "borderTop": "",
            "borderTopColor": "",
            "borderTopLeftRadius": "",
            "borderTopRightRadius": "",
            "borderTopStyle": "",
            "borderTopWidth": "",
            "borderWidth": "",
            "bottom": "",
            "boxShadow": "",
            "boxSizing": "",
            "breakAfter": "",
            "breakBefore": "",
            "breakInside": "",
            "bufferedRendering": "",
            "captionSide": "",
            "caretColor": "",
            "clear": "",
            "clip": "",
            "clipPath": "",
            "clipRule": "",
            "color": "",
            "colorInterpolation": "",
            "colorInterpolationFilters": "",
            "colorRendering": "",
            "colorScheme": "",
            "columnCount": "",
            "columnFill": "",
            "columnGap": "",
            "columnRule": "",
            "columnRuleColor": "",
            "columnRuleStyle": "",
            "columnRuleWidth": "",
            "columnSpan": "",
            "columnWidth": "",
            "columns": "",
            "contain": "",
            "containIntrinsicBlockSize": "",
            "containIntrinsicHeight": "",
            "containIntrinsicInlineSize": "",
            "containIntrinsicSize": "",
            "containIntrinsicWidth": "",
            "container": "",
            "containerName": "",
            "containerType": "",
            "content": "",
            "contentVisibility": "",
            "counterIncrement": "",
            "counterReset": "",
            "counterSet": "",
            "cursor": "",
            "cx": "",
            "cy": "",
            "d": "",
            "descentOverride": "",
            "direction": "",
            "display": "",
            "dominantBaseline": "",
            "emptyCells": "",
            "fallback": "",
            "fill": "",
            "fillOpacity": "",
            "fillRule": "",
            "filter": "",
            "flex": "",
            "flexBasis": "",
            "flexDirection": "",
            "flexFlow": "",
            "flexGrow": "",
            "flexShrink": "",
            "flexWrap": "",
            "float": "",
            "floodColor": "",
            "floodOpacity": "",
            "font": "",
            "fontDisplay": "",
            "fontFamily": "",
            "fontFeatureSettings": "",
            "fontKerning": "",
            "fontOpticalSizing": "",
            "fontPalette": "",
            "fontSize": "",
            "fontStretch": "",
            "fontStyle": "",
            "fontSynthesis": "",
            "fontSynthesisSmallCaps": "",
            "fontSynthesisStyle": "",
            "fontSynthesisWeight": "",
            "fontVariant": "",
            "fontVariantAlternates": "",
            "fontVariantCaps": "",
            "fontVariantEastAsian": "",
            "fontVariantLigatures": "",
            "fontVariantNumeric": "",
            "fontVariationSettings": "",
            "fontWeight": "",
            "forcedColorAdjust": "",
            "gap": "",
            "grid": "",
            "gridArea": "",
            "gridAutoColumns": "",
            "gridAutoFlow": "",
            "gridAutoRows": "",
            "gridColumn": "",
            "gridColumnEnd": "",
            "gridColumnGap": "",
            "gridColumnStart": "",
            "gridGap": "",
            "gridRow": "",
            "gridRowEnd": "",
            "gridRowGap": "",
            "gridRowStart": "",
            "gridTemplate": "",
            "gridTemplateAreas": "",
            "gridTemplateColumns": "",
            "gridTemplateRows": "",
            "height": "",
            "hyphenateCharacter": "",
            "hyphenateLimitChars": "",
            "hyphens": "",
            "imageOrientation": "",
            "imageRendering": "",
            "inherits": "",
            "initialLetter": "",
            "initialValue": "",
            "inlineSize": "",
            "inset": "",
            "insetBlock": "",
            "insetBlockEnd": "",
            "insetBlockStart": "",
            "insetInline": "",
            "insetInlineEnd": "",
            "insetInlineStart": "",
            "isolation": "",
            "justifyContent": "",
            "justifyItems": "",
            "justifySelf": "",
            "left": "",
            "letterSpacing": "",
            "lightingColor": "",
            "lineBreak": "",
            "lineGapOverride": "",
            "lineHeight": "",
            "listStyle": "",
            "listStyleImage": "",
            "listStylePosition": "",
            "listStyleType": "",
            "margin": "",
            "marginBlock": "",
            "marginBlockEnd": "",
            "marginBlockStart": "",
            "marginBottom": "",
            "marginInline": "",
            "marginInlineEnd": "",
            "marginInlineStart": "",
            "marginLeft": "",
            "marginRight": "",
            "marginTop": "",
            "marker": "",
            "markerEnd": "",
            "markerMid": "",
            "markerStart": "",
            "mask": "",
            "maskType": "",
            "mathDepth": "",
            "mathShift": "",
            "mathStyle": "",
            "maxBlockSize": "",
            "maxHeight": "",
            "maxInlineSize": "",
            "maxWidth": "",
            "minBlockSize": "",
            "minHeight": "",
            "minInlineSize": "",
            "minWidth": "",
            "mixBlendMode": "",
            "negative": "",
            "objectFit": "",
            "objectPosition": "",
            "objectViewBox": "",
            "offset": "",
            "offsetDistance": "",
            "offsetPath": "",
            "offsetRotate": "",
            "opacity": "",
            "order": "",
            "orphans": "",
            "outline": "",
            "outlineColor": "",
            "outlineOffset": "",
            "outlineStyle": "",
            "outlineWidth": "",
            "overflow": "",
            "overflowAnchor": "",
            "overflowClipMargin": "",
            "overflowWrap": "",
            "overflowX": "",
            "overflowY": "",
            "overrideColors": "",
            "overscrollBehavior": "",
            "overscrollBehaviorBlock": "",
            "overscrollBehaviorInline": "",
            "overscrollBehaviorX": "",
            "overscrollBehaviorY": "",
            "pad": "",
            "padding": "",
            "paddingBlock": "",
            "paddingBlockEnd": "",
            "paddingBlockStart": "",
            "paddingBottom": "",
            "paddingInline": "",
            "paddingInlineEnd": "",
            "paddingInlineStart": "",
            "paddingLeft": "",
            "paddingRight": "",
            "paddingTop": "",
            "page": "",
            "pageBreakAfter": "",
            "pageBreakBefore": "",
            "pageBreakInside": "",
            "pageOrientation": "",
            "paintOrder": "",
            "perspective": "",
            "perspectiveOrigin": "",
            "placeContent": "",
            "placeItems": "",
            "placeSelf": "",
            "pointerEvents": "",
            "position": "",
            "prefix": "",
            "quotes": "",
            "r": "",
            "range": "",
            "resize": "",
            "right": "",
            "rotate": "",
            "rowGap": "",
            "rubyPosition": "",
            "rx": "",
            "ry": "",
            "scale": "",
            "scrollBehavior": "",
            "scrollMargin": "",
            "scrollMarginBlock": "",
            "scrollMarginBlockEnd": "",
            "scrollMarginBlockStart": "",
            "scrollMarginBottom": "",
            "scrollMarginInline": "",
            "scrollMarginInlineEnd": "",
            "scrollMarginInlineStart": "",
            "scrollMarginLeft": "",
            "scrollMarginRight": "",
            "scrollMarginTop": "",
            "scrollPadding": "",
            "scrollPaddingBlock": "",
            "scrollPaddingBlockEnd": "",
            "scrollPaddingBlockStart": "",
            "scrollPaddingBottom": "",
            "scrollPaddingInline": "",
            "scrollPaddingInlineEnd": "",
            "scrollPaddingInlineStart": "",
            "scrollPaddingLeft": "",
            "scrollPaddingRight": "",
            "scrollPaddingTop": "",
            "scrollSnapAlign": "",
            "scrollSnapStop": "",
            "scrollSnapType": "",
            "scrollbarGutter": "",
            "shapeImageThreshold": "",
            "shapeMargin": "",
            "shapeOutside": "",
            "shapeRendering": "",
            "size": "",
            "sizeAdjust": "",
            "speak": "",
            "speakAs": "",
            "src": "",
            "stopColor": "",
            "stopOpacity": "",
            "stroke": "",
            "strokeDasharray": "",
            "strokeDashoffset": "",
            "strokeLinecap": "",
            "strokeLinejoin": "",
            "strokeMiterlimit": "",
            "strokeOpacity": "",
            "strokeWidth": "",
            "suffix": "",
            "symbols": "",
            "syntax": "",
            "system": "",
            "tabSize": "",
            "tableLayout": "",
            "textAlign": "",
            "textAlignLast": "",
            "textAnchor": "",
            "textCombineUpright": "",
            "textDecoration": "",
            "textDecorationColor": "",
            "textDecorationLine": "",
            "textDecorationSkipInk": "",
            "textDecorationStyle": "",
            "textDecorationThickness": "",
            "textEmphasis": "",
            "textEmphasisColor": "",
            "textEmphasisPosition": "",
            "textEmphasisStyle": "",
            "textIndent": "",
            "textOrientation": "",
            "textOverflow": "",
            "textRendering": "",
            "textShadow": "",
            "textSizeAdjust": "",
            "textTransform": "",
            "textUnderlineOffset": "",
            "textUnderlinePosition": "",
            "textWrap": "",
            "top": "",
            "touchAction": "",
            "transform": "",
            "transformBox": "",
            "transformOrigin": "",
            "transformStyle": "",
            "transition": "",
            "transitionDelay": "",
            "transitionDuration": "",
            "transitionProperty": "",
            "transitionTimingFunction": "",
            "translate": "",
            "unicodeBidi": "",
            "unicodeRange": "",
            "userSelect": "",
            "vectorEffect": "",
            "verticalAlign": "",
            "viewTransitionName": "",
            "visibility": "",
            "webkitAlignContent": "",
            "webkitAlignItems": "",
            "webkitAlignSelf": "",
            "webkitAnimation": "",
            "webkitAnimationDelay": "",
            "webkitAnimationDirection": "",
            "webkitAnimationDuration": "",
            "webkitAnimationFillMode": "",
            "webkitAnimationIterationCount": "",
            "webkitAnimationName": "",
            "webkitAnimationPlayState": "",
            "webkitAnimationTimingFunction": "",
            "webkitAppRegion": "",
            "webkitAppearance": "",
            "webkitBackfaceVisibility": "",
            "webkitBackgroundClip": "",
            "webkitBackgroundOrigin": "",
            "webkitBackgroundSize": "",
            "webkitBorderAfter": "",
            "webkitBorderAfterColor": "",
            "webkitBorderAfterStyle": "",
            "webkitBorderAfterWidth": "",
            "webkitBorderBefore": "",
            "webkitBorderBeforeColor": "",
            "webkitBorderBeforeStyle": "",
            "webkitBorderBeforeWidth": "",
            "webkitBorderBottomLeftRadius": "",
            "webkitBorderBottomRightRadius": "",
            "webkitBorderEnd": "",
            "webkitBorderEndColor": "",
            "webkitBorderEndStyle": "",
            "webkitBorderEndWidth": "",
            "webkitBorderHorizontalSpacing": "",
            "webkitBorderImage": "",
            "webkitBorderRadius": "",
            "webkitBorderStart": "",
            "webkitBorderStartColor": "",
            "webkitBorderStartStyle": "",
            "webkitBorderStartWidth": "",
            "webkitBorderTopLeftRadius": "",
            "webkitBorderTopRightRadius": "",
            "webkitBorderVerticalSpacing": "",
            "webkitBoxAlign": "",
            "webkitBoxDecorationBreak": "",
            "webkitBoxDirection": "",
            "webkitBoxFlex": "",
            "webkitBoxOrdinalGroup": "",
            "webkitBoxOrient": "",
            "webkitBoxPack": "",
            "webkitBoxReflect": "",
            "webkitBoxShadow": "",
            "webkitBoxSizing": "",
            "webkitClipPath": "",
            "webkitColumnBreakAfter": "",
            "webkitColumnBreakBefore": "",
            "webkitColumnBreakInside": "",
            "webkitColumnCount": "",
            "webkitColumnGap": "",
            "webkitColumnRule": "",
            "webkitColumnRuleColor": "",
            "webkitColumnRuleStyle": "",
            "webkitColumnRuleWidth": "",
            "webkitColumnSpan": "",
            "webkitColumnWidth": "",
            "webkitColumns": "",
            "webkitFilter": "",
            "webkitFlex": "",
            "webkitFlexBasis": "",
            "webkitFlexDirection": "",
            "webkitFlexFlow": "",
            "webkitFlexGrow": "",
            "webkitFlexShrink": "",
            "webkitFlexWrap": "",
            "webkitFontFeatureSettings": "",
            "webkitFontSmoothing": "",
            "webkitHighlight": "",
            "webkitHyphenateCharacter": "",
            "webkitJustifyContent": "",
            "webkitLineBreak": "",
            "webkitLineClamp": "",
            "webkitLocale": "",
            "webkitLogicalHeight": "",
            "webkitLogicalWidth": "",
            "webkitMarginAfter": "",
            "webkitMarginBefore": "",
            "webkitMarginEnd": "",
            "webkitMarginStart": "",
            "webkitMask": "",
            "webkitMaskBoxImage": "",
            "webkitMaskBoxImageOutset": "",
            "webkitMaskBoxImageRepeat": "",
            "webkitMaskBoxImageSlice": "",
            "webkitMaskBoxImageSource": "",
            "webkitMaskBoxImageWidth": "",
            "webkitMaskClip": "",
            "webkitMaskComposite": "",
            "webkitMaskImage": "",
            "webkitMaskOrigin": "",
            "webkitMaskPosition": "",
            "webkitMaskPositionX": "",
            "webkitMaskPositionY": "",
            "webkitMaskRepeat": "",
            "webkitMaskRepeatX": "",
            "webkitMaskRepeatY": "",
            "webkitMaskSize": "",
            "webkitMaxLogicalHeight": "",
            "webkitMaxLogicalWidth": "",
            "webkitMinLogicalHeight": "",
            "webkitMinLogicalWidth": "",
            "webkitOpacity": "",
            "webkitOrder": "",
            "webkitPaddingAfter": "",
            "webkitPaddingBefore": "",
            "webkitPaddingEnd": "",
            "webkitPaddingStart": "",
            "webkitPerspective": "",
            "webkitPerspectiveOrigin": "",
            "webkitPerspectiveOriginX": "",
            "webkitPerspectiveOriginY": "",
            "webkitPrintColorAdjust": "",
            "webkitRtlOrdering": "",
            "webkitRubyPosition": "",
            "webkitShapeImageThreshold": "",
            "webkitShapeMargin": "",
            "webkitShapeOutside": "",
            "webkitTapHighlightColor": "",
            "webkitTextCombine": "",
            "webkitTextDecorationsInEffect": "",
            "webkitTextEmphasis": "",
            "webkitTextEmphasisColor": "",
            "webkitTextEmphasisPosition": "",
            "webkitTextEmphasisStyle": "",
            "webkitTextFillColor": "",
            "webkitTextOrientation": "",
            "webkitTextSecurity": "",
            "webkitTextSizeAdjust": "",
            "webkitTextStroke": "",
            "webkitTextStrokeColor": "",
            "webkitTextStrokeWidth": "",
            "webkitTransform": "",
            "webkitTransformOrigin": "",
            "webkitTransformOriginX": "",
            "webkitTransformOriginY": "",
            "webkitTransformOriginZ": "",
            "webkitTransformStyle": "",
            "webkitTransition": "",
            "webkitTransitionDelay": "",
            "webkitTransitionDuration": "",
            "webkitTransitionProperty": "",
            "webkitTransitionTimingFunction": "",
            "webkitUserDrag": "",
            "webkitUserModify": "",
            "webkitUserSelect": "",
            "webkitWritingMode": "",
            "whiteSpace": "",
            "whiteSpaceCollapse": "",
            "widows": "",
            "width": "",
            "willChange": "",
            "wordBreak": "",
            "wordSpacing": "",
            "wordWrap": "",
            "writingMode": "",
            "x": "",
            "y": "",
            "zIndex": "",
            "zoom": ""
        },
        timeout_index: 1,
        timeout_obj: {},
        interval_index: 1,
        interval_obj: {},

        document_all_count: 0,
        ids: {},

    },
    out: globalThis.out,
    qiao_log: console.log,
};
